### ISSUE TITLE
Fail with http://IP

### ISSUE THREAD

**Issue by thEpisode** [droope/droopescan#19]
Hi, first of all your tool is awesome!.

I use Droopescan with url and works perfectly but when I try to use their IP the tool crash:

* URL: supresencia.com, 54.200.205.140
* OS: Ubuntu Server 16.04 x64
* Installation: PIP and manual (git clone...)
* Success command : ./droopescan scan -u supresencia.com --output json
* Fail command: ./droopescan scan -u http://54.200.205.140 --output json
* Output with `--debug-requests`:
[head] http://54.200.205.140/ None 200
[get] http://54.200.205.140/wp-admin/wp-admin.css None FAILED (<class 'requests.exceptions.TooManyRedirects'>: Exceeded 30 redirects.)
Traceback (most recent call last):
  File "./droopescan", line 5, in <module>
    droopescan.main()
  File "/home/thEpisode/droopescan/dscan/droopescan.py", line 55, in main
    ds.run()
  File "/home/thEpisode/.local/lib/python2.7/site-packages/cement/core/foundation.py", line 764, in run
    self.controller._dispatch()
  File "/home/thEpisode/.local/lib/python2.7/site-packages/cement/core/controller.py", line 466, in _dispatch
    return func()
  File "/home/thEpisode/.local/lib/python2.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/home/thEpisode/droopescan/dscan/plugins/internal/scan.py", line 115, in default
    follow_redirects)
  File "/home/thEpisode/droopescan/dscan/plugins/internal/scan.py", line 231, in _process_cms_identify
    if inst.cms_identify(url, opts['timeout'], self._generate_headers(host_header)) == True:
  File "/home/thEpisode/droopescan/dscan/plugins/internal/base_plugin_internal.py", line 921, in cms_identify
    headers)
  File "/home/thEpisode/droopescan/dscan/plugins/internal/base_plugin_internal.py", line 838, in enumerate_file_hash
    r = self.session.get(url + file_url, timeout=timeout, headers=headers)
  File "/home/thEpisode/droopescan/dscan/common/output.py", line 199, in get
    return self._print('get', *args, **kwargs)
  File "/home/thEpisode/droopescan/dscan/common/output.py", line 179, in _print
    r = sess_method(*args, **kwargs)
  File "/home/thEpisode/.local/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/thEpisode/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/thEpisode/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/thEpisode/.local/lib/python2.7/site-packages/requests/sessions.py", line 140, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

Thanks

**Comment by thEpisode** [comment]
Reverse Proxy detect, sorry 😄

**Comment by droope** [comment]
All good! lemme know if you have any other issues.
