### ISSUE TITLE
When website isn't available crash

### ISSUE THREAD

**Issue by thEpisode** [droope/droopescan#21]
Hi, I'm trying to test a site in developing mode, sometimes this is unavailable without any advertise. When I run Droopescan this crash, I think is a try-catch in the code. And JSON result isn't showed
 
* Output of run with `--debug-requests`:
[head] http://localhost:3000/ None FAILED (<class 'requests.exceptions.ConnectionError'>: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c099b33d0>: Failed to establish a new connection: [Errno 111] Connection refused',)))
Traceback (most recent call last):
  File "./droopescan", line 5, in <module>
    droopescan.main()
  File "/home/thEpisode/droopescan/dscan/droopescan.py", line 55, in main
    ds.run()
  File "/home/thEpisode/.local/lib/python2.7/site-packages/cement/core/foundation.py", line 764, in run
    self.controller._dispatch()
  File "/home/thEpisode/.local/lib/python2.7/site-packages/cement/core/controller.py", line 466, in _dispatch
    return func()
  File "/home/thEpisode/.local/lib/python2.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/home/thEpisode/droopescan/dscan/plugins/internal/scan.py", line 115, in default
    follow_redirects)
  File "/home/thEpisode/droopescan/dscan/plugins/internal/scan.py", line 224, in _process_cms_identify
    url, host_header = self.determine_redirect(url, host_header, opts)
  File "/home/thEpisode/droopescan/dscan/plugins/internal/base_plugin_internal.py", line 488, in determine_redirect
    opts['timeout'], self._generate_headers(host_header))
  File "/home/thEpisode/droopescan/dscan/plugins/internal/base_plugin_internal.py", line 454, in _determine_redirect
    r = requests_verb(url, timeout=timeout, headers=headers, allow_redirects=False)
  File "/home/thEpisode/droopescan/dscan/common/output.py", line 196, in head
    return self._print('head', *args, **kwargs)
  File "/home/thEpisode/droopescan/dscan/common/output.py", line 179, in _print
    r = sess_method(*args, **kwargs)
  File "/home/thEpisode/.local/lib/python2.7/site-packages/requests/sessions.py", line 543, in head
    return self.request('HEAD', url, **kwargs)
  File "/home/thEpisode/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/thEpisode/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/thEpisode/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c099b33d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
* OS & installation method: Ubuntu Server 16.04, pip and git clone
* Code: ./droopescan scan -u localhost:3000 --output json --debug-requests
* Expected result: {error:"Site seems to be down", ...}

**Comment by droope** [comment]
Hi there,

This crash is consistent with droopescan's current design parameters: on scanning multiple sites, errors are silently ignored and when scanning an individual site errors result in a fatal error. 

I plan a re-work of json output in the future and I can see the value in your suggestion for future releases.

Thanks,
Pedro

**Comment by thEpisode** [comment]
I understand, thank you so much
