### ISSUE TITLE
Drupal Scan Issue

### ISSUE THREAD

**Issue by darryllane** [droope/droopescan#6]
installed via pip and attempted to execute a druapl scan. Presented with the following output:

droopescan scan drupal --url (url removed)
Traceback (most recent call last):
  File "./droopescan", line 9, in <module>
    droopescan.main()
  File "/root/Scripts/droopescan/dscan/droopescan.py", line 46, in main
    ds.run()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 520, in run
    self.controller._dispatch()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 455, in _dispatch
    func()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 461, in _dispatch
    func()
  File "/root/Scripts/droopescan/dscan/plugins/drupal.py", line 40, in drupal
    self.plugin_init()
  File "/root/Scripts/droopescan/dscan/plugins/internal/base_plugin_internal.py", line 222, in plugin_init
    self._general_init(output=output, debug_requests=debug_requests)
  File "/root/Scripts/droopescan/dscan/plugins/internal/base_plugin_internal.py", line 64, in _general_init
    a = requests.adapters.HTTPAdapter(pool_maxsize=5000)
AttributeError: 'module' object has no attribute 'adapters'

**Comment by droope** [comment]
Hi Darryl,

I am sorry about the delay with the response! Somehow this didn't make it into my inbox.

It is an issue with the version of requests installed in Kali. It can be resolved by executing the following command in a root command shell:

<pre>
pip install -U requests
</pre>

Please let me know if this resolves it and I'll close the issue.

Thanks,
Pedro

**Comment by droope** [comment]
Hi @darryllane,

Let me know if this does not resolve the issue for you. You can update droopescan by executing:

<pre>
pip install -U droopescan
</pre>

In the future I may do some more Kali testing, there's definitely a wide range of people using it.

Ta,
Pedro
