### ISSUE TITLE
Kali 1.0.1- x64 - droopescan run problem 

### ISSUE THREAD

**Issue by JohnnyAMD** [droope/droopescan#7]
Hi, I got installed as follow: 

http://www.darknet.org.uk/2015/02/droopescan-plugin-based-cms-security-scanner/

Everything went fine. Now I'm trying to use it and I'm getting the following error message:

"
Traceback (most recent call last):
  File "/usr/local/bin/droopescan", line 9, in <module>
    droopescan.main()
  File "/usr/local/lib/python2.7/dist-packages/dscan/droopescan.py", line 46, in main
    ds.run()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 520, in run
    self.controller._dispatch()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 455, in _dispatch
    func()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 461, in _dispatch
    func()
  File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/drupal.py", line 40, in drupal
    self.plugin_init()
  File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 228, in plugin_init
    self._general_init(output=output, debug_requests=debug_requests)
  File "/usr/local/lib/python2.7/dist-packages/dscan/plugins/internal/base_plugin_internal.py", line 72, in _general_init
    self.out.warn(old_req)
AttributeError: 'NoneType' object has no attribute 'warn'
"

Any ideas what's going on?

Thanks.

**Comment by droope** [comment]
Hi @JohnnyAMD,

Thanks for reporting this.

Who would have thunk, the order of factors does alter the product!

I've fixed it in the latest release. You can get it by running the following command:

<pre>
pip install -U droopescan
</pre>

Ta,
Pedro

**Comment by JohnnyAMD** [comment]
Awesome. Let's try it.

Have a great day mate.

-Johnny
